#' Get simplified names for NCBI sequences
#'
#' @param ids A character vector of valid NCBI UIDs or accession numbers.
#' @param database A character name of an NCBI database. Defaults to \code{"nuccore"}, or the non-redundant nucleotide database (NR).
#'     For a complete list of options run \code{rentrez::entrez_db_searchable()}
#' @param sequence.name An optional sequence name.
#' @param include.species.name A logical argument specifying whether to include the species name in the sequence name. Defaults to \code{TRUE}.
#' @param include.accession A logical argument specifying whether to include the GenBank Accession number in the sequence name. Defaults to \code{TRUE}.
#' @param separator A character to use to separate the components of sequence names. Defaults to the underscore.
#'
#' @details This function is intended as a user-friendly wrapper for \code{rentrez::entrez_summary} and accepts other arguments to that function.
#'
#' @return Returns an character vector of NCBI IDs. These are the \code{esearch} object \code{ids} elements as generated by \code{rentrez::entrez_search}.
#'
#' @source Dave Angelini \email{david.r.angelini@@gmail.com} [aut, cre]
#'
#' @export
#'
#' @examples
#' accession.ids <- c("EF591774.1", "AF055971.2", "AF055967.2", "AF055927.2", "AY296172.1", "AF294303.1", "AF294297.1", "AF055976.2", "AF055945.2", "AF294317.1", "AY296196.1", "AF055966.2", "AF055939.2", "AF055940.2", "AY296195.1", "AY263052.1", "AY296163.1")
#' short.names <- simplify.sequence.names(ids  = accession.ids, sequence.name = "ND2")

simplify.sequence.names <- function (
  ids,
  database = "nuccore",
  sequence.name = "",
  separator = "_",
  ...
)
{ # Begin the function

  # Don't bother running anything if dependent package isn't installed!
  if (!require(rentrez)) {
    stop("Please run  `install.packages('rentrez')`  first.")
  }

  # Vet the input
  if (!exists(quote(ids))) {
    stop("No argument specified to `ids`. (See the help entry: `?simplify.sequence.names`.)\n")
  }
  if (class(ids)[1] != "character") {
    stop("Error in argument `ids`. (See the help entry: `?simplify.sequence.names`.)\n")
  }
  if (class(database)[1] != "character") {
    stop("Error in argument `database`. (See the help entry: `?simplify.sequence.names`.)\n")
  } else { database <- database[1] }
  if (!(database %in% entrez_dbs())) {
    warning("You have entered an invalid value for the argument `database`. Defaulting to `database = 'nuccore'.`\n")
    database <- "nuccore"
  }
  if (class(sequence.name)[1] != "character") {
    stop("Error in argument `sequence.name`. (See the help entry: `?simplify.sequence.names`.)\n")
  } else { sequence.name <- sequence.name[1] }
  if (class(separator)[1] != "character") {
    stop("Error in argument `separator`. (See the help entry: `?simplify.sequence.names`.)\n")
  } else { separator <- separator[1] }
  # End preliminary vetting of the input and arguments

  # Simplify names
  seq.details <- entrez_summary(db=database, id=ids, ...)

  if (is(seq.details)=="esummary_list") {
    taxids <- unname(unlist(lapply(seq.details, function(x) { x$taxid } )))
    taxonomy.details <- entrez_summary(db="taxonomy", id=taxids)
    species.names <- unname(unlist(lapply(taxonomy.details, function(x) { paste0(x$genus, separator, x$species) } )))
    seq.names <- unlist(lapply(1:length(seq.details), function(i) {
      paste0(species.names[i], separator, sequence.name, separator, seq.details[[i]]$accessionversion)
    }))
  } else {
    if (is(seq.details)=="esummary") {
      taxids <- seq.details$taxid
      taxonomy.details <- entrez_summary(db="taxonomy", id=taxids)
      species.names <- paste0(taxonomy.details$genus, separator, taxonomy.details$species)
      seq.names <- paste0(species.names, separator, sequence.name, separator, seq.details$accessionversion)
    }
  }

  seq.names <- gsub(paste0(separator,separator),separator,seq.names)

  return(seq.names)

} # End of function
